### ISSUE TITLE
Mask will not display on unsaturated pixels.

### ISSUE THREAD

**Issue by antoniaelsen** [aelsen/pixelsort#2]
The mask is added as a hue filter -- thus it relies on S and L values. Change to addition of a semi-opaque green to RGB values.

**Comment by aelsen** [comment]
Fixed in 6277692ec8cc882864a1a5f2944940a3046d3072.

**Comment by antoniaelsen** [comment]
Fixed in 6277692ec8cc882864a1a5f2944940a3046d3072.
